Fix use of bytes instances for Python 3.x (issue #1)
Traceback (most recent call last):
  File "./fetchcommandwrapper", line 17, in <module>
    main()
  File "./modules/fetchcommandwrapper/main.py", line 191, in main
    supported_mirror_uris = [e for e in gentoo_mirrors() if supported(e)]
  File "./modules/fetchcommandwrapper/main.py", line 93, in gentoo_mirrors
    return out.rstrip('\n').split(' ')
TypeError: a bytes-like object is required, not 'str'